// Code generated by go-swagger; DO NOT EDIT.

// Package restapi A Todo list application
//
//  From the todo list tutorial on goswagger.io
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
