// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: rpc_chunk_file/service/proto/upload.proto

package upload

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqBuffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ReqBuffer) Reset() {
	*x = ReqBuffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chunk_file_service_proto_upload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqBuffer) ProtoMessage() {}

func (x *ReqBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chunk_file_service_proto_upload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqBuffer.ProtoReflect.Descriptor instead.
func (*ReqBuffer) Descriptor() ([]byte, []int) {
	return file_rpc_chunk_file_service_proto_upload_proto_rawDescGZIP(), []int{0}
}

func (x *ReqBuffer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResBuffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *ResBuffer) Reset() {
	*x = ResBuffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chunk_file_service_proto_upload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResBuffer) ProtoMessage() {}

func (x *ResBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chunk_file_service_proto_upload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResBuffer.ProtoReflect.Descriptor instead.
func (*ResBuffer) Descriptor() ([]byte, []int) {
	return file_rpc_chunk_file_service_proto_upload_proto_rawDescGZIP(), []int{1}
}

func (x *ResBuffer) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

var File_rpc_chunk_file_service_proto_upload_proto protoreflect.FileDescriptor

var file_rpc_chunk_file_service_proto_upload_proto_rawDesc = []byte{
	0x0a, 0x29, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63,
	0x22, 0x1f, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x27, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x3d, 0x0a, 0x0d, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x42,
	0x75, 0x66, 0x66, 0x65, 0x72, 0x1a, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x42,
	0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0x00, 0x28, 0x01, 0x42, 0x1f, 0x5a, 0x1d, 0x72, 0x70, 0x63,
	0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rpc_chunk_file_service_proto_upload_proto_rawDescOnce sync.Once
	file_rpc_chunk_file_service_proto_upload_proto_rawDescData = file_rpc_chunk_file_service_proto_upload_proto_rawDesc
)

func file_rpc_chunk_file_service_proto_upload_proto_rawDescGZIP() []byte {
	file_rpc_chunk_file_service_proto_upload_proto_rawDescOnce.Do(func() {
		file_rpc_chunk_file_service_proto_upload_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_chunk_file_service_proto_upload_proto_rawDescData)
	})
	return file_rpc_chunk_file_service_proto_upload_proto_rawDescData
}

var file_rpc_chunk_file_service_proto_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_chunk_file_service_proto_upload_proto_goTypes = []interface{}{
	(*ReqBuffer)(nil), // 0: rpc.ReqBuffer
	(*ResBuffer)(nil), // 1: rpc.ResBuffer
}
var file_rpc_chunk_file_service_proto_upload_proto_depIdxs = []int32{
	0, // 0: rpc.UploadService.Upload:input_type -> rpc.ReqBuffer
	1, // 1: rpc.UploadService.Upload:output_type -> rpc.ResBuffer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_chunk_file_service_proto_upload_proto_init() }
func file_rpc_chunk_file_service_proto_upload_proto_init() {
	if File_rpc_chunk_file_service_proto_upload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_chunk_file_service_proto_upload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqBuffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_chunk_file_service_proto_upload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResBuffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_chunk_file_service_proto_upload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_chunk_file_service_proto_upload_proto_goTypes,
		DependencyIndexes: file_rpc_chunk_file_service_proto_upload_proto_depIdxs,
		MessageInfos:      file_rpc_chunk_file_service_proto_upload_proto_msgTypes,
	}.Build()
	File_rpc_chunk_file_service_proto_upload_proto = out.File
	file_rpc_chunk_file_service_proto_upload_proto_rawDesc = nil
	file_rpc_chunk_file_service_proto_upload_proto_goTypes = nil
	file_rpc_chunk_file_service_proto_upload_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UploadServiceClient is the client API for UploadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UploadServiceClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (UploadService_UploadClient, error)
}

type uploadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUploadServiceClient(cc grpc.ClientConnInterface) UploadServiceClient {
	return &uploadServiceClient{cc}
}

func (c *uploadServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (UploadService_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UploadService_serviceDesc.Streams[0], "/rpc.UploadService/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &uploadServiceUploadClient{stream}
	return x, nil
}

type UploadService_UploadClient interface {
	Send(*ReqBuffer) error
	CloseAndRecv() (*ResBuffer, error)
	grpc.ClientStream
}

type uploadServiceUploadClient struct {
	grpc.ClientStream
}

func (x *uploadServiceUploadClient) Send(m *ReqBuffer) error {
	return x.ClientStream.SendMsg(m)
}

func (x *uploadServiceUploadClient) CloseAndRecv() (*ResBuffer, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ResBuffer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UploadServiceServer is the server API for UploadService service.
type UploadServiceServer interface {
	Upload(UploadService_UploadServer) error
}

// UnimplementedUploadServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUploadServiceServer struct {
}

func (*UnimplementedUploadServiceServer) Upload(UploadService_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}

func RegisterUploadServiceServer(s *grpc.Server, srv UploadServiceServer) {
	s.RegisterService(&_UploadService_serviceDesc, srv)
}

func _UploadService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UploadServiceServer).Upload(&uploadServiceUploadServer{stream})
}

type UploadService_UploadServer interface {
	SendAndClose(*ResBuffer) error
	Recv() (*ReqBuffer, error)
	grpc.ServerStream
}

type uploadServiceUploadServer struct {
	grpc.ServerStream
}

func (x *uploadServiceUploadServer) SendAndClose(m *ResBuffer) error {
	return x.ServerStream.SendMsg(m)
}

func (x *uploadServiceUploadServer) Recv() (*ReqBuffer, error) {
	m := new(ReqBuffer)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _UploadService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.UploadService",
	HandlerType: (*UploadServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _UploadService_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "rpc_chunk_file/service/proto/upload.proto",
}
