// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: rpc_list/proto/list.proto

package list

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqBuffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text []string `protobuf:"bytes,1,rep,name=Text,proto3" json:"Text,omitempty"`
}

func (x *ReqBuffer) Reset() {
	*x = ReqBuffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_list_proto_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqBuffer) ProtoMessage() {}

func (x *ReqBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_proto_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqBuffer.ProtoReflect.Descriptor instead.
func (*ReqBuffer) Descriptor() ([]byte, []int) {
	return file_rpc_list_proto_list_proto_rawDescGZIP(), []int{0}
}

func (x *ReqBuffer) GetText() []string {
	if x != nil {
		return x.Text
	}
	return nil
}

type ResBuffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//
	//Status Field
	//0 = Failed
	//1 = Success
	TotalElement int32 `protobuf:"varint,1,opt,name=TotalElement,proto3" json:"TotalElement,omitempty"`
}

func (x *ResBuffer) Reset() {
	*x = ResBuffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_list_proto_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResBuffer) ProtoMessage() {}

func (x *ResBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_list_proto_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResBuffer.ProtoReflect.Descriptor instead.
func (*ResBuffer) Descriptor() ([]byte, []int) {
	return file_rpc_list_proto_list_proto_rawDescGZIP(), []int{1}
}

func (x *ResBuffer) GetTotalElement() int32 {
	if x != nil {
		return x.TotalElement
	}
	return 0
}

var File_rpc_list_proto_list_proto protoreflect.FileDescriptor

var file_rpc_list_proto_list_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x70, 0x63, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63,
	0x22, 0x1f, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78,
	0x74, 0x22, 0x2f, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x22,
	0x0a, 0x0c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x32, 0x3f, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x30, 0x0a, 0x0c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x42, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x1a, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x42, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x72, 0x70, 0x63, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_list_proto_list_proto_rawDescOnce sync.Once
	file_rpc_list_proto_list_proto_rawDescData = file_rpc_list_proto_list_proto_rawDesc
)

func file_rpc_list_proto_list_proto_rawDescGZIP() []byte {
	file_rpc_list_proto_list_proto_rawDescOnce.Do(func() {
		file_rpc_list_proto_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_list_proto_list_proto_rawDescData)
	})
	return file_rpc_list_proto_list_proto_rawDescData
}

var file_rpc_list_proto_list_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_list_proto_list_proto_goTypes = []interface{}{
	(*ReqBuffer)(nil), // 0: rpc.ReqBuffer
	(*ResBuffer)(nil), // 1: rpc.ResBuffer
}
var file_rpc_list_proto_list_proto_depIdxs = []int32{
	0, // 0: rpc.ListService.TotalElement:input_type -> rpc.ReqBuffer
	1, // 1: rpc.ListService.TotalElement:output_type -> rpc.ResBuffer
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_list_proto_list_proto_init() }
func file_rpc_list_proto_list_proto_init() {
	if File_rpc_list_proto_list_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_list_proto_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqBuffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_list_proto_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResBuffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_list_proto_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_list_proto_list_proto_goTypes,
		DependencyIndexes: file_rpc_list_proto_list_proto_depIdxs,
		MessageInfos:      file_rpc_list_proto_list_proto_msgTypes,
	}.Build()
	File_rpc_list_proto_list_proto = out.File
	file_rpc_list_proto_list_proto_rawDesc = nil
	file_rpc_list_proto_list_proto_goTypes = nil
	file_rpc_list_proto_list_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ListServiceClient is the client API for ListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListServiceClient interface {
	TotalElement(ctx context.Context, in *ReqBuffer, opts ...grpc.CallOption) (*ResBuffer, error)
}

type listServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListServiceClient(cc grpc.ClientConnInterface) ListServiceClient {
	return &listServiceClient{cc}
}

func (c *listServiceClient) TotalElement(ctx context.Context, in *ReqBuffer, opts ...grpc.CallOption) (*ResBuffer, error) {
	out := new(ResBuffer)
	err := c.cc.Invoke(ctx, "/rpc.ListService/TotalElement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListServiceServer is the server API for ListService service.
type ListServiceServer interface {
	TotalElement(context.Context, *ReqBuffer) (*ResBuffer, error)
}

// UnimplementedListServiceServer can be embedded to have forward compatible implementations.
type UnimplementedListServiceServer struct {
}

func (*UnimplementedListServiceServer) TotalElement(context.Context, *ReqBuffer) (*ResBuffer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalElement not implemented")
}

func RegisterListServiceServer(s *grpc.Server, srv ListServiceServer) {
	s.RegisterService(&_ListService_serviceDesc, srv)
}

func _ListService_TotalElement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBuffer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServiceServer).TotalElement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.ListService/TotalElement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServiceServer).TotalElement(ctx, req.(*ReqBuffer))
	}
	return interceptor(ctx, in, info, handler)
}

var _ListService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.ListService",
	HandlerType: (*ListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TotalElement",
			Handler:    _ListService_TotalElement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_list/proto/list.proto",
}
